import "dotenv/config";
import { prisma } from "@repo/db";

async function MoreSampleData() {
  // await MoreSampleContentData();
  // await MoreSampleEmployeeData();
  await moreSampleContentData();
}

async function moreSampleContentData() {
  //Content sample data
  await prisma.content.createMany({
    data: [
      {
        title: "Commercial Lines Underwriting Guide",
        url: "https://example.com/commercial-lines-guide",
        contentOwner: "Andrew Blanchard",
        forPosition: "UNDERWRITER",
        lastModifiedTime: new Date("2025-03-15"),
        expirationTime: new Date("2026-03-15"),
        contentType: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Risk Appetite Framework",
        url: "https://example.com/risk-appetite-framework",
        contentOwner: "Max Messina",
        forPosition: "UNDERWRITER",
        lastModifiedTime: new Date("2025-02-10"),
        expirationTime: new Date("2026-02-10"),
        contentType: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Property Underwriting Checklist",
        url: "https://example.com/property-underwriting-checklist",
        contentOwner: "Mario Evangjeli",
        forPosition: "UNDERWRITER",
        lastModifiedTime: new Date("2025-04-01"),
        expirationTime: new Date("2026-04-01"),
        contentType: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "Casualty Loss Ratio Analysis",
        url: "https://example.com/casualty-loss-ratio",
        contentOwner: "Pranya Paudyal",
        forPosition: "UNDERWRITER",
        lastModifiedTime: new Date("2025-01-20"),
        expirationTime: new Date("2026-01-20"),
        contentType: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "New Business Submission Workflow",
        url: "https://example.com/new-business-submission",
        contentOwner: "Kyle Spinney",
        forPosition: "UNDERWRITER",
        lastModifiedTime: new Date("2025-03-28"),
        expirationTime: new Date("2026-03-28"),
        contentType: "WORKFLOW",
        status: "IN_USE",
      },
      {
        title: "Reinsurance Treaty Summary",
        url: "https://example.com/reinsurance-treaty-summary",
        contentOwner: "Cole Bender",
        forPosition: "UNDERWRITER",
        lastModifiedTime: new Date("2025-02-14"),
        expirationTime: new Date("2026-02-14"),
        contentType: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Account Renewal Decision Guide",
        url: "https://example.com/account-renewal-decision",
        contentOwner: "Aiden Custance",
        forPosition: "UNDERWRITER",
        lastModifiedTime: new Date("2025-03-05"),
        expirationTime: new Date("2026-03-05"),
        contentType: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "Excess and Surplus Lines Procedures",
        url: "https://example.com/excess-surplus-lines",
        contentOwner: "Tara Bastien",
        forPosition: "UNDERWRITER",
        lastModifiedTime: new Date("2025-01-30"),
        expirationTime: new Date("2026-01-30"),
        contentType: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Underwriting Authority Matrix",
        url: "https://example.com/underwriting-authority-matrix",
        contentOwner: "Lexi Marcossa",
        forPosition: "UNDERWRITER",
        lastModifiedTime: new Date("2025-04-02"),
        expirationTime: new Date("2026-04-02"),
        contentType: "REFERENCE",
        status: "IN_USE",
      },
      {
        title: "Pricing Model User Guide",
        url: "https://example.com/pricing-model-user-guide",
        contentOwner: "James Carter",
        forPosition: "UNDERWRITER",
        lastModifiedTime: new Date("2025-03-18"),
        expirationTime: new Date("2026-03-18"),
        contentType: "WORKFLOW",
        status: "AVAILABLE",
      },

      // 14 new Business Analyst entries
      {
        title: "Requirements Gathering Template",
        url: "https://example.com/requirements-gathering",
        contentOwner: "Rachel Kim",
        forPosition: "BUSINESS_ANALYST",
        lastModifiedTime: new Date("2025-03-10"),
        expirationTime: new Date("2026-03-10"),
        contentType: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "Process Mapping Guide",
        url: "https://example.com/process-mapping-guide",
        contentOwner: "Tom Nguyen",
        forPosition: "BUSINESS_ANALYST",
        lastModifiedTime: new Date("2025-02-20"),
        expirationTime: new Date("2026-02-20"),
        contentType: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Stakeholder Communication Plan",
        url: "https://example.com/stakeholder-communication",
        contentOwner: "Sarah Patel",
        forPosition: "BUSINESS_ANALYST",
        lastModifiedTime: new Date("2025-03-25"),
        expirationTime: new Date("2026-03-25"),
        contentType: "WORKFLOW",
        status: "IN_USE",
      },
      {
        title: "User Story Writing Standards",
        url: "https://example.com/user-story-standards",
        contentOwner: "David Moore",
        forPosition: "BUSINESS_ANALYST",
        lastModifiedTime: new Date("2025-01-15"),
        expirationTime: new Date("2026-01-15"),
        contentType: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "UAT Sign-Off Checklist",
        url: "https://example.com/uat-signoff-checklist",
        contentOwner: "Jessica Ward",
        forPosition: "BUSINESS_ANALYST",
        lastModifiedTime: new Date("2025-03-15"),
        expirationTime: new Date("2026-03-15"),
        contentType: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "Business Case Development Guide",
        url: "https://example.com/business-case-guide",
        contentOwner: "Mark Ellis",
        forPosition: "BUSINESS_ANALYST",
        lastModifiedTime: new Date("2025-02-05"),
        expirationTime: new Date("2026-02-05"),
        contentType: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Data Flow Diagram Standards",
        url: "https://example.com/data-flow-diagram-standards",
        contentOwner: "Amanda Torres",
        forPosition: "BUSINESS_ANALYST",
        lastModifiedTime: new Date("2025-01-28"),
        expirationTime: new Date("2026-01-28"),
        contentType: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Sprint Planning Procedure",
        url: "https://example.com/sprint-planning-procedure",
        contentOwner: "Chris Lawson",
        forPosition: "BUSINESS_ANALYST",
        lastModifiedTime: new Date("2025-03-01"),
        expirationTime: new Date("2026-03-01"),
        contentType: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "Gap Analysis Framework",
        url: "https://example.com/gap-analysis-framework",
        contentOwner: "Megan Foster",
        forPosition: "BUSINESS_ANALYST",
        lastModifiedTime: new Date("2025-04-05"),
        expirationTime: new Date("2026-04-05"),
        contentType: "REFERENCE",
        status: "IN_USE",
      },
      {
        title: "Change Request Management Workflow",
        url: "https://example.com/change-request-workflow",
        contentOwner: "Daniel Hayes",
        forPosition: "BUSINESS_ANALYST",
        lastModifiedTime: new Date("2025-02-25"),
        expirationTime: new Date("2026-02-25"),
        contentType: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "System Integration Test Plan",
        url: "https://example.com/system-integration-test-plan",
        contentOwner: "Laura Chen",
        forPosition: "BUSINESS_ANALYST",
        lastModifiedTime: new Date("2025-03-20"),
        expirationTime: new Date("2026-03-20"),
        contentType: "WORKFLOW",
        status: "AVAILABLE",
      },
      {
        title: "KPI Dashboard Reference",
        url: "https://example.com/kpi-dashboard-reference",
        contentOwner: "Kevin Grant",
        forPosition: "BUSINESS_ANALYST",
        lastModifiedTime: new Date("2025-01-10"),
        expirationTime: new Date("2026-01-10"),
        contentType: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Vendor Evaluation Scorecard",
        url: "https://example.com/vendor-evaluation-scorecard",
        contentOwner: "Nina Rowe",
        forPosition: "BUSINESS_ANALYST",
        lastModifiedTime: new Date("2025-02-18"),
        expirationTime: new Date("2026-02-18"),
        contentType: "REFERENCE",
        status: "AVAILABLE",
      },
      {
        title: "Project Closure Report Template",
        url: "https://example.com/project-closure-template",
        contentOwner: "Eric Sullivan",
        forPosition: "BUSINESS_ANALYST",
        lastModifiedTime: new Date("2025-03-30"),
        expirationTime: new Date("2026-03-30"),
        contentType: "WORKFLOW",
        status: "AVAILABLE",
      },
    ],
  });
}

MoreSampleData()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
